# Generated by Django 2.2 on 2020-07-28 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('happy_breeder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='last_mate_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 7, 40, 13, 594639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_refresh_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 7, 40, 13, 594467, tzinfo=utc)),
        ),
    ]
